import { SqlSource } from "../types";

export const SQL_PREREQUISITES = [
  {
    id: 1,
    topic: "Basics",
    title: "SELECT, WHERE, ORDER BY, LIMIT",
    description: "Understand the core structure of a SQL query. Practice filtering rows, sorting results, and limiting output.",
    docUrl: "https://www.postgresql.org/docs/current/tutorial-select.html",
    completed: false
  },
  {
    id: 2,
    topic: "Aggregation",
    title: "GROUP BY and HAVING",
    description: "Learn how to group rows that have the same values and filter these groups using HAVING.",
    docUrl: "https://www.postgresql.org/docs/current/tutorial-agg.html",
    completed: false
  },
  {
    id: 3,
    topic: "Joins",
    title: "INNER, LEFT, RIGHT, FULL, CROSS",
    description: "Understand how to combine rows from two or more tables based on a related column between them.",
    docUrl: "https://www.postgresql.org/docs/current/tutorial-join.html",
    completed: false
  },
  {
    id: 4,
    topic: "Advanced Queries",
    title: "Subqueries and CTEs",
    description: "Learn how to nest queries using subqueries and the WITH clause (Common Table Expressions) for better readability.",
    docUrl: "https://www.postgresql.org/docs/current/queries-with.html",
    completed: false
  },
  {
    id: 5,
    topic: "Window Functions",
    title: "ROW_NUMBER, RANK, LAG, LEAD",
    description: "Master window functions to perform calculations across a set of table rows that are somehow related to the current row.",
    docUrl: "https://www.postgresql.org/docs/current/tutorial-window.html",
    completed: false
  },
  {
    id: 6,
    topic: "PostgreSQL Specifics",
    title: "Date/Time, Strings, JSONB",
    description: "Familiarize yourself with Postgres specific functions like DATE_TRUNC, EXTRACT, ILIKE, and handling JSON data.",
    docUrl: "https://www.postgresql.org/docs/current/functions.html",
    completed: false
  }
];

export const SQL_PROBLEMS = [
  // Basics
  { id: 1, title: "Select All Columns from Employees", difficulty: "Easy", topics: ["Basics"], url: "https://leetcode.com/problems/find-customer-referee/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Basics"], status: "pending", attempts: 0 },
  { id: 2, title: "Recyclable and Low Fat Products", difficulty: "Easy", topics: ["Basics"], url: "https://leetcode.com/problems/recyclable-and-low-fat-products/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Basics"], status: "pending", attempts: 0 },
  { id: 3, title: "Big Countries", difficulty: "Easy", topics: ["Basics"], url: "https://leetcode.com/problems/big-countries/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Basics"], status: "pending", attempts: 0 },
  { id: 4, title: "Article Views I", difficulty: "Easy", topics: ["Basics", "Distinct"], url: "https://leetcode.com/problems/article-views-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Basics"], status: "pending", attempts: 0 },
  
  // Joins
  { id: 5, title: "Replace Employee ID With The Unique Identifier", difficulty: "Easy", topics: ["Joins"], url: "https://leetcode.com/problems/replace-employee-id-with-the-unique-identifier/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Joins"], status: "pending", attempts: 0 },
  { id: 6, title: "Product Sales Analysis I", difficulty: "Easy", topics: ["Joins"], url: "https://leetcode.com/problems/product-sales-analysis-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Joins"], status: "pending", attempts: 0 },
  { id: 7, title: "Customer Who Visited but Did Not Make Any Transactions", difficulty: "Easy", topics: ["Joins", "Aggregation"], url: "https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Joins", "Aggregation"], status: "pending", attempts: 0 },
  { id: 8, title: "Rising Temperature", difficulty: "Easy", topics: ["Joins", "Date/Time"], url: "https://leetcode.com/problems/rising-temperature/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Joins"], status: "pending", attempts: 0 },

  // Aggregation
  { id: 9, title: "Not Boring Movies", difficulty: "Easy", topics: ["Aggregation", "Math"], url: "https://leetcode.com/problems/not-boring-movies/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Aggregation"], status: "pending", attempts: 0 },
  { id: 10, title: "Average Selling Price", difficulty: "Easy", topics: ["Aggregation", "Joins"], url: "https://leetcode.com/problems/average-selling-price/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Aggregation"], status: "pending", attempts: 0 },
  { id: 11, title: "Project Employees I", difficulty: "Easy", topics: ["Aggregation", "Joins"], url: "https://leetcode.com/problems/project-employees-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Aggregation"], status: "pending", attempts: 0 },
  { id: 12, title: "Percentage of Users Attended a Contest", difficulty: "Easy", topics: ["Aggregation"], url: "https://leetcode.com/problems/percentage-of-users-attended-a-contest/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Aggregation"], status: "pending", attempts: 0 },

  // Subqueries & CTEs
  { id: 13, title: "Employees Whose Manager Left the Company", difficulty: "Easy", topics: ["Subqueries"], url: "https://leetcode.com/problems/employees-whose-manager-left-the-company/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Advanced Queries"], status: "pending", attempts: 0 },
  { id: 14, title: "Exchange Seats", difficulty: "Medium", topics: ["CTEs", "CASE"], url: "https://leetcode.com/problems/exchange-seats/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Advanced Queries"], status: "pending", attempts: 0 },
  { id: 15, title: "Movie Rating", difficulty: "Medium", topics: ["CTEs", "Joins", "Aggregation"], url: "https://leetcode.com/problems/movie-rating/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Advanced Queries"], status: "pending", attempts: 0 },
  { id: 16, title: "Restaurant Growth", difficulty: "Medium", topics: ["CTEs", "Window Functions"], url: "https://leetcode.com/problems/restaurant-growth/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Advanced Queries", "Window Functions"], status: "pending", attempts: 0 },

  // Window Functions
  { id: 17, title: "Department Top Three Salaries", difficulty: "Hard", topics: ["Window Functions", "Joins"], url: "https://leetcode.com/problems/department-top-three-salaries/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window Functions"], status: "pending", attempts: 0 },
  { id: 18, title: "Investments in 2016", difficulty: "Medium", topics: ["Window Functions"], url: "https://leetcode.com/problems/investments-in-2016/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window Functions"], status: "pending", attempts: 0 },
  { id: 19, title: "Game Play Analysis IV", difficulty: "Medium", topics: ["Window Functions"], url: "https://leetcode.com/problems/game-play-analysis-iv/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window Functions"], status: "pending", attempts: 0 },
  
  // Advanced & Postgres Specific
  { id: 20, title: "User Activity for the Past 30 Days I", difficulty: "Easy", topics: ["Date/Time", "Aggregation"], url: "https://leetcode.com/problems/user-activity-for-the-past-30-days-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["PostgreSQL Specifics"], status: "pending", attempts: 0 },
  { id: 21, title: "Group Sold Products By The Date", difficulty: "Easy", topics: ["Strings", "Aggregation"], url: "https://leetcode.com/problems/group-sold-products-by-the-date/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["PostgreSQL Specifics"], status: "pending", attempts: 0 },
  { id: 22, title: "List the Products Ordered in a Period", difficulty: "Easy", topics: ["Date/Time", "Joins"], url: "https://leetcode.com/problems/list-the-products-ordered-in-a-period/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["PostgreSQL Specifics"], status: "pending", attempts: 0 },
  { id: 23, title: "Recyclable and Low Fat Products", difficulty: "Easy", topics: ["SELECT","WHERE"], companyTags: ["Amazon"], url: "https://leetcode.com/problems/recyclable-and-low-fat-products/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["SELECT","WHERE"], status: "pending", attempts: 0 },
  { id: 24, title: "Find Customer Referee", difficulty: "Easy", topics: ["WHERE","NULL"], companyTags: null, url: "https://leetcode.com/problems/find-customer-referee/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["WHERE","NULL"], status: "pending", attempts: 0 },
  { id: 25, title: "Big Countries", difficulty: "Easy", topics: ["WHERE"], companyTags: null, url: "https://leetcode.com/problems/big-countries/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["WHERE"], status: "pending", attempts: 0 },
  { id: 26, title: "Article Views I", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/article-views-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 27, title: "Invalid Tweets", difficulty: "Easy", topics: ["WHERE"], companyTags: null, url: "https://leetcode.com/problems/invalid-tweets/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["WHERE"], status: "pending", attempts: 0 },
  { id: 28, title: "Second Highest Salary", difficulty: "Medium", topics: ["Subquery","Window"], companyTags: ["Amazon","Google"], url: "https://leetcode.com/problems/second-highest-salary/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Subquery","Window"], status: "pending", attempts: 0 },
  { id: 29, title: "Consecutive Numbers", difficulty: "Medium", topics: ["Self Join"], companyTags: null, url: "https://leetcode.com/problems/consecutive-numbers/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Self Join"], status: "pending", attempts: 0 },
  { id: 30, title: "Department Top Three Salaries", difficulty: "Hard", topics: ["Window Functions","RANK"], companyTags: ["FAANG"], url: "https://leetcode.com/problems/department-top-three-salaries/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window Functions","RANK"], status: "pending", attempts: 0 },
  { id: 31, title: "Managers with at Least 5 Direct Reports", difficulty: "Medium", topics: ["GROUP BY","HAVING"], companyTags: null, url: "https://leetcode.com/problems/managers-with-at-least-5-direct-reports/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY","HAVING"], status: "pending", attempts: 0 },
  { id: 32, title: "Confirmation Rate", difficulty: "Medium", topics: ["JOIN","AVG"], companyTags: ["Meta"], url: "https://leetcode.com/problems/confirmation-rate/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN","AVG"], status: "pending", attempts: 0 },
  { id: 33, title: "Product Sales Analysis III", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/product-sales-analysis-iii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 34, title: "Classes With at Least 5 Students", difficulty: "Medium", topics: ["GROUP BY","HAVING"], companyTags: null, url: "https://leetcode.com/problems/classes-with-at-least-5-students/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY","HAVING"], status: "pending", attempts: 0 },
  { id: 35, title: "Find Followers Count", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/find-followers-count/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 36, title: "Customers Who Bought All Products", difficulty: "Medium", topics: ["GROUP BY","HAVING"], companyTags: null, url: "https://leetcode.com/problems/customers-who-bought-all-products/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY","HAVING"], status: "pending", attempts: 0 },
  { id: 37, title: "Employee Bonus", difficulty: "Easy", topics: ["LEFT JOIN"], companyTags: null, url: "https://leetcode.com/problems/employee-bonus/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["LEFT JOIN"], status: "pending", attempts: 0 },
  { id: 38, title: "Movie Rating", difficulty: "Medium", topics: ["GROUP BY","CASE"], companyTags: null, url: "https://leetcode.com/problems/movie-rating/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY","CASE"], status: "pending", attempts: 0 },
  { id: 39, title: "Restaurant Growth", difficulty: "Medium", topics: ["Window","AVG"], companyTags: null, url: "https://leetcode.com/problems/restaurant-growth/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window","AVG"], status: "pending", attempts: 0 },
  { id: 40, title: "Investments in 2016", difficulty: "Medium", topics: ["SUM"], companyTags: null, url: "https://leetcode.com/problems/investments-in-2016/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["SUM"], status: "pending", attempts: 0 },
  { id: 41, title: "Friend Requests II: Who Has the Most Friends", difficulty: "Medium", topics: ["UNION"], companyTags: null, url: "https://leetcode.com/problems/friend-requests-ii-who-has-the-most-friends/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["UNION"], status: "pending", attempts: 0 },
  { id: 42, title: "Exchange Seats", difficulty: "Medium", topics: ["Self Join"], companyTags: null, url: "https://leetcode.com/problems/exchange-seats/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Self Join"], status: "pending", attempts: 0 },
  { id: 43, title: "Employees Earning More Than Their Managers", difficulty: "Easy", topics: ["Self Join"], companyTags: null, url: "https://leetcode.com/problems/employees-earning-more-than-their-managers/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Self Join"], status: "pending", attempts: 0 },
  { id: 44, title: "Duplicate Emails", difficulty: "Easy", topics: ["GROUP BY","HAVING"], companyTags: null, url: "https://leetcode.com/problems/duplicate-emails/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY","HAVING"], status: "pending", attempts: 0 },
  { id: 45, title: "Customers Who Never Order", difficulty: "Easy", topics: ["LEFT JOIN"], companyTags: null, url: "https://leetcode.com/problems/customers-who-never-order/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["LEFT JOIN"], status: "pending", attempts: 0 },
  { id: 46, title: "Department Highest Salary", difficulty: "Medium", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/department-highest-salary/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 47, title: "Rising Temperature", difficulty: "Easy", topics: ["Self Join"], companyTags: null, url: "https://leetcode.com/problems/rising-temperature/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Self Join"], status: "pending", attempts: 0 },
  { id: 48, title: "Product Sales Analysis I", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/product-sales-analysis-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 49, title: "Product Sales Analysis II", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/product-sales-analysis-ii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 50, title: "Histogram of Tweets", difficulty: "Easy", topics: ["GROUP BY"], companyTags: ["Twitter"], url: "https://datalemur.com/questions/sql-histogram-tweets", source: "DataLemur" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 51, title: "Page With No Likes", difficulty: "Easy", topics: ["LEFT JOIN"], companyTags: ["Facebook"], url: "https://datalemur.com/questions/sql-page-with-no-likes", source: "DataLemur" as SqlSource, prerequisiteTopics: ["LEFT JOIN"], status: "pending", attempts: 0 },
  { id: 52, title: "Laptop vs. Mobile Viewership", difficulty: "Easy", topics: ["CASE"], companyTags: ["NY Times"], url: "https://datalemur.com/questions/sql-laptop-mobile-viewership", source: "DataLemur" as SqlSource, prerequisiteTopics: ["CASE"], status: "pending", attempts: 0 },
  { id: 53, title: "Highest-Grossing Items", difficulty: "Medium", topics: ["Window"], companyTags: ["Amazon"], url: "https://datalemur.com/questions/sql-highest-grossing", source: "DataLemur" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 54, title: "User’s Third Transaction", difficulty: "Medium", topics: ["ROW_NUMBER"], companyTags: ["Uber"], url: "https://datalemur.com/questions/sql-users-third-transaction", source: "DataLemur" as SqlSource, prerequisiteTopics: ["ROW_NUMBER"], status: "pending", attempts: 0 },
  { id: 55, title: "Tweets' Rolling Averages", difficulty: "Medium", topics: ["Window"], companyTags: ["Twitter"], url: "https://datalemur.com/questions/sql-tweets-rolling-averages", source: "DataLemur" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 56, title: "Top Three Salaries", difficulty: "Medium", topics: ["DENSE_RANK"], companyTags: ["FAANG"], url: "https://datalemur.com/questions/sql-top-three-salaries", source: "DataLemur" as SqlSource, prerequisiteTopics: ["DENSE_RANK"], status: "pending", attempts: 0 },
  { id: 57, title: "Well Paid Employees", difficulty: "Easy", topics: ["Self Join"], companyTags: null, url: "https://datalemur.com/questions/sql-well-paid-employees", source: "DataLemur" as SqlSource, prerequisiteTopics: ["Self Join"], status: "pending", attempts: 0 },
  { id: 58, title: "Second Highest Salary", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://datalemur.com/questions/sql-second-highest-salary", source: "DataLemur" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 59, title: "Signup Activation Rate", difficulty: "Medium", topics: ["JOIN"], companyTags: ["TikTok"], url: "https://datalemur.com/questions/sql-signup-activation-rate", source: "DataLemur" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 60, title: "Average Review Ratings", difficulty: "Easy", topics: ["GROUP BY"], companyTags: ["Amazon"], url: "https://datalemur.com/questions/sql-average-review-ratings", source: "DataLemur" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 61, title: "Teams Power Users", difficulty: "Easy", topics: ["GROUP BY"], companyTags: ["Microsoft"], url: "https://datalemur.com/questions/sql-teams-power-users", source: "DataLemur" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 62, title: "New And Existing Users", difficulty: "Hard", topics: ["Window","Date"], companyTags: ["Apple"], url: "https://platform.stratascratch.com/coding/2028-new-and-existing-users", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["Window","Date"], status: "pending", attempts: 0 },
  { id: 63, title: "Activity Rank", difficulty: "Medium", topics: ["Window"], companyTags: ["Google"], url: "https://platform.stratascratch.com/coding/10351-activity-rank", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 64, title: "Rank Variance Per Country", difficulty: "Hard", topics: ["Window"], companyTags: ["Meta"], url: "https://platform.stratascratch.com/coding/2007-rank-variance-per-country", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 65, title: "Apple Product Counts", difficulty: "Medium", topics: ["CASE"], companyTags: ["Apple"], url: "https://platform.stratascratch.com/coding", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["CASE"], status: "pending", attempts: 0 },
  { id: 66, title: "Monthly Active Users", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://platform.stratascratch.com/coding", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 67, title: "Game Play Analysis I", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/game-play-analysis-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 68, title: "Game Play Analysis II", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/game-play-analysis-ii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 69, title: "Game Play Analysis III", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/game-play-analysis-iii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 70, title: "Game Play Analysis IV", difficulty: "Hard", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/game-play-analysis-iv/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 71, title: "Find the Quiet Students in All Exams", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/find-the-quiet-students-in-all-exams/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 72, title: "All People Report to the Given Manager", difficulty: "Medium", topics: ["Recursive CTE"], companyTags: null, url: "https://leetcode.com/problems/all-people-report-to-the-given-manager/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Recursive CTE"], status: "pending", attempts: 0 },
  { id: 73, title: "Number of Unique Subjects Taught by Each Teacher", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/number-of-unique-subjects-taught-by-each-teacher/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 74, title: "Average Selling Price", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/average-selling-price/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 75, title: "Project Employees I", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/project-employees-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 76, title: "Project Employees II", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/project-employees-ii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 77, title: "Project Employees III", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/project-employees-iii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 78, title: "Bank Account Summary", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/bank-account-summary/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 79, title: "Immediate Food Delivery I", difficulty: "Easy", topics: ["CASE"], companyTags: null, url: "https://leetcode.com/problems/immediate-food-delivery-i/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["CASE"], status: "pending", attempts: 0 },
  { id: 80, title: "Immediate Food Delivery II", difficulty: "Medium", topics: ["AVG"], companyTags: null, url: "https://leetcode.com/problems/immediate-food-delivery-ii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["AVG"], status: "pending", attempts: 0 },
  { id: 81, title: "Find Users With Valid E-Mails", difficulty: "Easy", topics: ["REGEXP"], companyTags: null, url: "https://leetcode.com/problems/find-users-with-valid-e-mails/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["REGEXP"], status: "pending", attempts: 0 },
  { id: 82, title: "Patients With a Condition", difficulty: "Easy", topics: ["LIKE"], companyTags: null, url: "https://leetcode.com/problems/patients-with-a-condition/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["LIKE"], status: "pending", attempts: 0 },
  { id: 83, title: "Replace Employee ID With The Unique Identifier", difficulty: "Easy", topics: ["LEFT JOIN"], companyTags: null, url: "https://leetcode.com/problems/replace-employee-id-with-the-unique-identifier/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["LEFT JOIN"], status: "pending", attempts: 0 },
  { id: 84, title: "Customer Who Visited but Did Not Make Any Transactions", difficulty: "Easy", topics: ["LEFT JOIN"], companyTags: null, url: "https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["LEFT JOIN"], status: "pending", attempts: 0 },
  { id: 85, title: "Sales Person", difficulty: "Easy", topics: ["LEFT JOIN"], companyTags: null, url: "https://leetcode.com/problems/sales-person/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["LEFT JOIN"], status: "pending", attempts: 0 },
  { id: 86, title: "Triangle Judgement", difficulty: "Easy", topics: ["CASE"], companyTags: null, url: "https://leetcode.com/problems/triangle-judgement/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["CASE"], status: "pending", attempts: 0 },
  { id: 87, title: "Consecutive Available Seats", difficulty: "Medium", topics: ["Self Join"], companyTags: null, url: "https://leetcode.com/problems/consecutive-available-seats/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Self Join"], status: "pending", attempts: 0 },
  { id: 88, title: "Product Price at a Given Date", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/product-price-at-a-given-date/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 89, title: "Last Person to Fit in the Bus", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/problems/last-person-to-fit-in-the-bus/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 90, title: "Number of Calls Between Two Persons", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/number-of-calls-between-two-persons/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 91, title: "Count Student Number in Departments", difficulty: "Easy", topics: ["LEFT JOIN"], companyTags: null, url: "https://leetcode.com/problems/count-student-number-in-departments/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["LEFT JOIN"], status: "pending", attempts: 0 },
  { id: 92, title: "Find Total Time Spent by Each Employee", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/find-total-time-spent-by-each-employee/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 93, title: "Repeated Purchases", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://datalemur.com/questions", source: "DataLemur" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 94, title: "Ad Campaign Performance", difficulty: "Medium", topics: ["JOIN"], companyTags: null, url: "https://datalemur.com/questions", source: "DataLemur" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 95, title: "Top 5 Highest Paid Employees", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://platform.stratascratch.com/coding", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 96, title: "Customer Revenue by Month", difficulty: "Medium", topics: ["GROUP BY"], companyTags: null, url: "https://platform.stratascratch.com/coding", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 97, title: "Y-on-Y Growth Rate", difficulty: "Hard", topics: ["Window"], companyTags: null, url: "https://platform.stratascratch.com/coding", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 98, title: "Marketing Campaign Success", difficulty: "Medium", topics: ["JOIN"], companyTags: null, url: "https://platform.stratascratch.com/coding", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 99, title: "Sales Analysis III", difficulty: "Easy", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/sales-analysis-iii/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 100, title: "List the Products Ordered in a Period", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/list-the-products-ordered-in-a-period/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 101, title: "Find the Team Size", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/find-the-team-size/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 102, title: "The Number of Employees Which Report to Each Employee", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/the-number-of-employees-which-report-to-each-employee/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 103, title: "The Number of Rich Customers", difficulty: "Easy", topics: ["WHERE"], companyTags: null, url: "https://leetcode.com/problems/the-number-of-rich-customers/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["WHERE"], status: "pending", attempts: 0 },
  { id: 104, title: "Maximum Total Importance of Roads", difficulty: "Medium", topics: ["GROUP BY"], companyTags: null, url: "https://leetcode.com/problems/maximum-total-importance-of-roads/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["GROUP BY"], status: "pending", attempts: 0 },
  { id: 105, title: "Count Salary Categories", difficulty: "Medium", topics: ["CASE"], companyTags: null, url: "https://leetcode.com/problems/count-salary-categories/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["CASE"], status: "pending", attempts: 0 },
  { id: 106, title: "Average Time of Process per Machine", difficulty: "Easy", topics: ["JOIN"], companyTags: null, url: "https://leetcode.com/problems/average-time-of-process-per-machine/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["JOIN"], status: "pending", attempts: 0 },
  { id: 107, title: "Employee Task Duration", difficulty: "Medium", topics: ["Window"], companyTags: null, url: "https://leetcode.com/studyplan/top-sql-50/", source: "LeetCode" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
  { id: 108, title: "User Session Activity", difficulty: "Hard", topics: ["Window"], companyTags: null, url: "https://platform.stratascratch.com/coding", source: "StratasScratch" as SqlSource, prerequisiteTopics: ["Window"], status: "pending", attempts: 0 },
];
